CLUSTAL W (1.81) multiple sequence alignment

sp|Q14588|ZN234_HUMAN        ----------------------MTTFKEGLTFKDVAVVFTEEELGLLDPVQRNLYQDVML
sp|Q9NYT6|ZN226_HUMAN        ----------------------MNMFKEAVTFKDVAVAFTEEELGLLGPAQRKLYRDVMV
sp|Q9UK10|ZN225_HUMAN        ----------------------MTTLKEAVTFKDVAVVFTEEELRLLDLAQRKLYREVML
sp|Q9UK13|ZN221_HUMAN        MISPSLELLHSGLCKFPEVEGKMTTFKEAVTFKDVAVVFTEEELGLLDPAQRKLYRDVML
sp|Q9NZL3|ZN224_HUMAN        ----------------------MTTFKEAMTFKDVAVVFTEEELGLLDLAQRKLYRDVML
sp|Q9UK12-2|ZN222_HUMAN      -------------MIDSGEKKPGRRAEEAVTFKDVAVIFTEEELGLLDPAQRKLYRDVML
sp|Q12901|ZN155_HUMAN        ----------------------MTTFKEAVTFKDVAVVFTEEELGLLDPAQRKLYRDVML
sp|Q14590|ZN235_HUMAN        ----------------------MTKFQEAVTFKDVAVAFTEEELGLLDSAQRKLYRDVML
sp|Q02386|ZNF45_HUMAN        ----------------------MTKSKEAVTFKDVAVVFSEEELQLLDLAQRKLYRDVML
                                                       :*.:******* *:**** **. .**:**.:**:

sp|Q14588|ZN234_HUMAN        ENFRNLLSVGHHPFKHDVF-LLEKEKKLDIMKTATQRKGKSADKIQSEVETVPEAG----
sp|Q9NYT6|ZN226_HUMAN        ENFRNLLSVGHPPFKQDVS-PIERNEQLWIMTTATRRQGNLGEKNQSKLITVQDRE----
sp|Q9UK10|ZN225_HUMAN        ENFRNLLSVGHQSLHRDTF-HFLKEEKFWMMETATQREGNLGGKIQMEMETVSESG----
sp|Q9UK13|ZN221_HUMAN        ENFRNLLSVGNQPFHQDTF-HFLGKEKFWKMKTTSQREGNSGGKIQIEMETVPEAG----
sp|Q9NZL3|ZN224_HUMAN        ENFRNLLSVGHQAFHRDTF-HFLREEKIWMMKTAIQREGNSGDKIQTEMETVSEAG----
sp|Q9UK12-2|ZN222_HUMAN      ENFRNLLSVGHQPFHGDTF-HFLREEKFWVMGTTSQREGNLGGKIQTEMETVPEAG----
sp|Q12901|ZN155_HUMAN        ENFRNLLSVGHQPFHQDTC-HFLREEKFWMMGTATQREGNSGGKIQTELESVPEAG----
sp|Q14590|ZN235_HUMAN        ENFRNLVSVGHQSFKPDMISQLEREEKLWMKELQTQRGKHSGDRNQNEMATLHKAGLRCF
sp|Q02386|ZNF45_HUMAN        ENFRNVVSVGHQS-TPDGLPQLEREEKLWMMKMATQRDNSSGAKNLKEMETLQEVGLRYL
                             *****::***: .   *    :  ::::       .*    . .   :: :: .      

sp|Q14588|ZN234_HUMAN        RHEELYWGQIWKQIASDLIKYEDSMIS----ISRFPRQGDLS------------------
sp|Q9NYT6|ZN226_HUMAN        SEEELSCWQIWQQIANDLTRCQDSMIN----NSQCHKQGDFPYQVGTELSIQISEDENYI
sp|Q9UK10|ZN225_HUMAN        THEGLFSHQTWEQISSDLTRFQDSMVN----SFQFSKQDDMP------------------
sp|Q9UK13|ZN221_HUMAN        PHEEWSCQQIWEQIASDLTRSQNSIRN----SSQFFKEGDVP------------------
sp|Q9NZL3|ZN224_HUMAN        THQEWSFQQIWEKIASDLTRSQDLMIN----SSQFSKEGDFP------------------
sp|Q9UK12-2|ZN222_HUMAN      THEEFSCKQIWEQIASDLTRSQDTTIS----NSQLFEQDDNP------------------
sp|Q12901|ZN155_HUMAN        AHEEWSCQQIWEQIAKDLTRSQDSIIN----NSQFFENGDVP------------------
sp|Q14590|ZN235_HUMAN        SLGELSCWQIKRHIASKLARSQDSMINIEGKSSQFPKHHDSP------------------
sp|Q02386|ZNF45_HUMAN        PHEELFCSQIWQQITRELIKYQDSVVNIQRTGCQLEKRDDLHYKDEGF------------
                                     * . :*: .* . ::   .      .     *                    

sp|Q14588|ZN234_HUMAN        -----------------------------------------------CQVRAGL------
sp|Q9NYT6|ZN226_HUMAN        VNKADGPNNTGNPEFPILRTQDSWRKTFLTESQRLNRDQQISIKNKLCQCKKGVDPIGWI
sp|Q9UK10|ZN225_HUMAN        -----------------------------------------------CQVDAGL------
sp|Q9UK13|ZN221_HUMAN        -----------------------------------------------CQIEARL------
sp|Q9NZL3|ZN224_HUMAN        -----------------------------------------------CQTEAGL------
sp|Q9UK12-2|ZN222_HUMAN      -----------------------------------------------SQIKARL------
sp|Q12901|ZN155_HUMAN        -----------------------------------------------SQVEAGL------
sp|Q14590|ZN235_HUMAN        -----------------------------------------------CQVGAGESIQASV
sp|Q02386|ZNF45_HUMAN        -----------------------------------------------SNQSSHLQV----
                                                                            .:           

sp|Q14588|ZN234_HUMAN        ---------------------------------YTTHTGQKFYQCDEYKKS---------
sp|Q9NYT6|ZN226_HUMAN        SHHDGHRVHKSEKSYRPNDYEKDNMKILTFDHNSMIHTGQKSYQCNECKKP---------
sp|Q9UK10|ZN225_HUMAN        ---------------------------------SIIHVRQKPSEGRTCKKS---------
sp|Q9UK13|ZN221_HUMAN        ---------------------------------SISHVQQKPYRCNECKQS---------
sp|Q9NZL3|ZN224_HUMAN        ---------------------------------SVIHTRQKSSQGNGYKPS---------
sp|Q9UK12-2|ZN222_HUMAN      ---------------------------------STVHTREKPFQGENCKQF---------
sp|Q12901|ZN155_HUMAN        ---------------------------------PTIHTGQKPSQGGKCKQS---------
sp|Q14590|ZN235_HUMAN        DDNCLVNHIGDHSSIIENQEFPTGKVPNSW---SKIYLNETQNYQRSCKQTQMKNKLCIF
sp|Q02386|ZNF45_HUMAN        ---------------------------------HRVHTGEKPYKGEHCVKS---------
                                                                 :  :.                   

sp|Q14588|ZN234_HUMAN        ------FTDVFNFDLHQQLHSGEKSHTCDECGKSFCYISALHIHQRVHMGEKCYKCDVCG
sp|Q9NYT6|ZN226_HUMAN        ------FSDLSSFDLHQQLQSGEKSLTCVERGKGFCYSPVLPVHQKVHVGEKL-KCDECG
sp|Q9UK10|ZN225_HUMAN        ------FSDVSVLDLHQQLQSREKSHTCDECGKSFCYSSALRIHQRVHMGEKLYNCDVCG
sp|Q9UK13|ZN221_HUMAN        ------FSDVSVFDLHQQSHSGEKSHTCGECGKSFCYSPALHIHQRVHMGEKCYKCDVCG
sp|Q9NZL3|ZN224_HUMAN        ------FSDVSHFDFHQQLHSGEKSHTCDECGKNFCYISALRIHQRVHMGEKCYKCDVCG
sp|Q9UK12-2|ZN222_HUMAN      ------FSDVSFFDLPQQLYSGEKSHTCDECGKSFCYISALHIHQRVHMGVKCYKCDVCG
sp|Q12901|ZN155_HUMAN        ------ISDVPIFDLPQQLYSEEKSYTCDECGKSICYISALHVHQRVHVGEKLFMCDVCG
sp|Q14590|ZN235_HUMAN        APYVDIFSCISHHHDDNIVHKRDKVHSNSDCGKDTLKVSPL-TQRSIHTGQKTYQGNECE
sp|Q02386|ZNF45_HUMAN        ------FSWSSHLQINQRAHAGEKPYKCEKCDNAFRRFSSLQAHQRVHSRAKSYTNDASY
                                   ::        :     :*  .  . .:     . *  :. :*   *    : . 

sp|Q14588|ZN234_HUMAN        KEFSQSSHLQTHQRVHTVEKPFKCVECGKGFSRRSTLTVHCKLHSGEKPYNCEECGRAFI
sp|Q9NYT6|ZN226_HUMAN        KEFSQGAHLQTHQKVHVIEKPYKCKQCGKGFSRRSALNVHCKVHTAEKPYNCEECGRAFS
sp|Q9UK10|ZN225_HUMAN        KEFNQSSHLQIHQRIHTGEKPFKCEQCGKGFSRRSGLYVHRKLHTGVKPHICEKCGKAFI
sp|Q9UK13|ZN221_HUMAN        KEFNQSSHLQTHQRVHTGEKPFKCGQCGKGFHSRSALNVHCKLHTGEKPYNCEECGKAFI
sp|Q9NZL3|ZN224_HUMAN        KEFSQSSHLQTHQRVHTGEKPFKCVECGKGFSRRSALNVHHKLHTGEKPYNCEECGKAFI
sp|Q9UK12-2|ZN222_HUMAN      KEFSQSSRLQTHQRVHTGEKPFKCEQCGKGFRCRSALKVHCKLHMREKPYNCEKCGKAFM
sp|Q12901|ZN155_HUMAN        KEFSQSSHLQTHQRVHTGEKPFKCEQCGKGFSRRSALNVHRKLHTGEKPYICEACGKAFI
sp|Q14590|ZN235_HUMAN        EAFNDSSSLELHKQVHLGKKSPACSTHEKDTSYSSGIPVQQSVRTGKKRYWCHECGKGFS
sp|Q02386|ZNF45_HUMAN        RSFSQRSHLPHHQRVPTGENPYKYEECGRNVGKSSHCQAPLIVHTGEKPYKCEECGVGFS
                               *.: : *  *:.:   ::.       ..    *   .   :.   * : *  ** .* 

sp|Q14588|ZN234_HUMAN        HASHLQEHQRIHTGEKPFKCDTCGKNFRRRSALNNHCMVHTGEKPYKCEDCGKCFTCSSN
sp|Q9NYT6|ZN226_HUMAN        QASHLQDHQRLHTGEKPFKCDACGKSFSRNSHLQSHQRVHTGEKPYKCEECGKGFICSSN
sp|Q9UK10|ZN225_HUMAN        HDSQLQEHQRIHTGEKPFKCDICCKSFRSRANLNRHSMVHMREKPFRCDTCGKSFGLKSA
sp|Q9UK13|ZN221_HUMAN        HDSQLQEHQRIHTGEKPFKCDICGKSFRVRSRLNRHSMVHTGEKAFRCDTCGKNFRQRSA
sp|Q9NZL3|ZN224_HUMAN        HDSQLQEHQRIHTGEKPFKCDICGKSFCGRSRLNRHSMVHTAEKPFRCDTCDKSFRQRSA
sp|Q9UK12-2|ZN222_HUMAN      HNFQLQKHHRIHTGEKPFKCEICGKSFCL----------------------------RSS
sp|Q12901|ZN155_HUMAN        HDSQLKEHKRIHTGEKPFKCDICGKTFYFRSRLKSHSMVHTGEKPFRCDTCDKSFHQRSA
sp|Q14590|ZN235_HUMAN        QSSNLQTHQRVHTGEKPYTCHECGKSFNQSSHLYAHLPIHTGEKPYRCDSCGKGFSRSTD
sp|Q02386|ZNF45_HUMAN        QRSYLQVHLKVHTGKKPYKCEECGKSFSWRSRLQAHERIHTGEKPYKCNACGKSFSYSSH
                             :   *: * .:***:**:.*  * *.*                               : 

sp|Q14588|ZN234_HUMAN        LRIHQRVHTGEKPYKCEECGKCFIQPSQFQAHRRIHTGEKPYVCKVCGKGFIYSSSFQAH
sp|Q9NYT6|ZN226_HUMAN        LYIHQRVHTGEKPYKCEECGKGFSRPSSLQAHQGVHTGEKSYICTVCGKGFTLSSNLQAH
sp|Q9UK10|ZN225_HUMAN        LNSHRMVHTGEKRYKCEECGKRFIYRQDLYKHQIDHTGEKPYNCKECGKSFRWASGLSRH
sp|Q9UK13|ZN221_HUMAN        LNSHSMVHIEEKPYKCEQCGKGFICRRDFCKHQMVHTGEKPYNCKECGKTFRWSSCLLNH
sp|Q9NZL3|ZN224_HUMAN        LNSHRMIHTGEKPYKCEECGKGFICRRDLYTHHMVHTGEKPYNCKECGKSFRWASCLLKH
sp|Q9UK12-2|ZN222_HUMAN      LNRHCMVHTAEKLYKSEKYGRGFIDRLDLHKHQMIHMGQKPYNCKECGKSFKWSSYLLVH
sp|Q12901|ZN155_HUMAN        LNRHCMVHTGEKPYRCEQCGKGFIGRLDFYKHQVVHTGEKPYNCKECGKSFRWSSCLLNH
sp|Q14590|ZN235_HUMAN        LNIHCRVHTGEKPYKCEVCGKGFTQRSHLQAHERIHTGEKPYKCGDCGKRFSCSSNLHTH
sp|Q02386|ZNF45_HUMAN        LNIHCRIHTGEKPYKCEECGKGFSVGSHLQAHQISHTGEKPYKCEECGKGFCRASNLLDH
                             *  *  :*  ** *..*  *. *     :  *   * *:*.* *  *** *  :* :  *

sp|Q14588|ZN234_HUMAN        QGVHTGEKPYKCNECGKSFRMKIHYQVHLVVHTGEKPYKCEVCGKAFRQSSYLKIHLKAH
sp|Q9NYT6|ZN226_HUMAN        QRVHTGEKPYKCNECGKSFRRNSHYQVHLVVHTGEKPYKCEICGKGFSQSSYLQIHQKAH
sp|Q9UK10|ZN225_HUMAN        VRVHSGETTFKCEECGKGFYTNSQRYSHQRAHSGEKPYRCEECGKGYKRRLDLDFHQRVH
sp|Q9UK13|ZN221_HUMAN        QQVHSGQKSFKCEECGKGFYTNSRRSSHQRSHNGEKPYNCEECGKDYKRRLDLEFHQRVH
sp|Q9NZL3|ZN224_HUMAN        QRVHSGEKPFKCEECGKGFYTNSQCYSHQRSHSGEKPYKCVECGKGYKRRLDLDFHQRVH
sp|Q9UK12-2|ZN222_HUMAN      QRVHT----------------------------GEKPYKCEECGKGYISKSGLDFHHRTH
sp|Q12901|ZN155_HUMAN        QRVHSGEKSFKCEECGKGFYTNSQLSSHQRSHSGEKPYKCEECGKGYVTKFNLDLHQRVH
sp|Q14590|ZN235_HUMAN        QRVHTEEKPYKCDECGKCFSLSFNLHSHQRVHTGEKPYKCEECGKGFSSASSFQSHQRVH
sp|Q02386|ZNF45_HUMAN        QRGHTGEKPYQCDACGKGFSRSSDFNIHFRVHTGEKPYKCEECGKGFSQASNLLAHQRGH
                                *:                            *****.*  *** :     :  * . *

sp|Q14588|ZN234_HUMAN        SVQKPFKCEECGQGFNQSSRLQIHQLIHTGEKPYKCEECGKGFSRRADLKIHCRIHTGE-
sp|Q9NYT6|ZN226_HUMAN        SIEKPFKCEECGQGFNQSSRLQIHQLIHTGEKPYKCEECGKGFSRRADLKIHCRIHTGE-
sp|Q9UK10|ZN225_HUMAN        RGEKPYNCKECGKSFGWASCLLNHQRIHSGEKPFKCEECGKRFTQNSQLYTHRRVHSGEK
sp|Q9UK13|ZN221_HUMAN        TGERPYNCKECGKSFGWASCLLKHQRLHSGEKPFKCEECGKRFTQSSQLHSHQTCHTGE-
sp|Q9NZL3|ZN224_HUMAN        TGEKLYNCKECGKSFSRAPCLLKHERLHSGEKPFQCEECGKRFTQNSHLHSHQRVHTGE-
sp|Q9UK12-2|ZN222_HUMAN      TGERSYNCDNCGKSFRHASSILNHKKLHCQRKPLKCEDCGKRLVCRSYCKDQQRDHSGE-
sp|Q12901|ZN155_HUMAN        TGERPYNCKECGKNFSRASSILNHKRLHCQKKPFKCEDCGKRLVHRTYRKDQPRDYSGE-
sp|Q14590|ZN235_HUMAN        TGEKPFRCNVCGKGFSQSSYFQAHQRVHTGEKPYKCEVCGKRFNWSLNLHNHQRVHTGE-
sp|Q02386|ZNF45_HUMAN        TGEKPYKCGTCGKGFSRSSDLNVHCRIHTGEKPYKCERCGKAFSQFSSLQVHQRVHTGE-
                               :. :.*  **:.* .:. :  *  :*   ** :** *** :        :   ::** 

sp|Q14588|ZN234_HUMAN        ---------------------------KPYNCEECGKVFSQASHLLTHQRVHSGEKPFKC
sp|Q9NYT6|ZN226_HUMAN        ---------------------------KPYNCEECGKVFRQASNLLAHQRVHSGEKPFKC
sp|Q9UK10|ZN225_HUMAN        PFKCEECGKRFTQNSQLYSHRRVHTGVKPYKCEECGKGFNSKFNLDMHQRVHTGERPYNC
sp|Q9UK13|ZN221_HUMAN        ---------------------------KLYKCEQCEKGYNSKFNLDMHQRVHGGERPYNC
sp|Q9NZL3|ZN224_HUMAN        ---------------------------KPYKCEKCGKGYNSKFNLDMHQKVHTGERPYNC
sp|Q9UK12-2|ZN222_HUMAN      ---------------------------NPSKCED--------------------------
sp|Q12901|ZN155_HUMAN        ---------------------------NPSKCED--------------------------
sp|Q14590|ZN235_HUMAN        ---------------------------KPYKCEECGKGFSQASNLQAHQSVHTGEKPFKC
sp|Q02386|ZNF45_HUMAN        ---------------------------KPYQCAECGKGFSVGSQLQAHQRCHTGEKPYQC
                                                        :  :* .                          

sp|Q14588|ZN234_HUMAN        EECGKSFSRSAHLQAHQKVHTGEKPYKCGECGKGFKWSLNLDMHQRVHTGEKPYTCGECG
sp|Q9NYT6|ZN226_HUMAN        EECGKSFGRSAHLQAHQKVHTGDKPYKCDECGKGFKWSLNLDMHQRVHTGEKPYKCGECG
sp|Q9UK10|ZN225_HUMAN        KECGKSFSRASSILNHKRLHGDEKPFKCEECGKRFTENSQLHSHQRVHTGEKPYKCEKCG
sp|Q9UK13|ZN221_HUMAN        KECGKSFGWASCLLKHQRLHSGEKPLKSGV------------------------------
sp|Q9NZL3|ZN224_HUMAN        KECGKSFGWASCLLKHQRLHSGEKPFKCEECGKRFTQNSQLHSHQRVHTGEKPYKCDECG
sp|Q9UK12-2|ZN222_HUMAN      ------------------------------------------------------------
sp|Q12901|ZN155_HUMAN        ------------------------------------------------------------
sp|Q14590|ZN235_HUMAN        DACQKRFSQASHLQAHQRVHTGEKPYKCDTCGKAFSQRSNLQVHQIIHTGEKPFKCEECG
sp|Q02386|ZNF45_HUMAN        EECGKGFCRASNFLAHRGVHTGEKPYRCDVCGKRFRQRSYLQAHQRVHTGERPYKCEECG
                                                                                         

sp|Q14588|ZN234_HUMAN        KHFSQASSLQLHQSVHTGEKPYKCDVCGKVFSRSSQLQYHRRVHTGEKPYKCEICGKRFS
sp|Q9NYT6|ZN226_HUMAN        KYFSQASSLQLHQSVHTGEKPYKCDVCGKVFSRSSQLQSHQRVHTGEKPYKCEICGKSFS
sp|Q9UK10|ZN225_HUMAN        KSFRWASTHLTHQRLHSREKLLQCEDCGKSIVHSSCLKDQQRDQSGEKTSKCEDCGKRYK
sp|Q9UK13|ZN221_HUMAN        ----WEEIYSEFTASFTSVSL---------------------------------CGRKAI
sp|Q9NZL3|ZN224_HUMAN        KGFSWSSTRLTHQRRHSRETPLKCEQHGKNIVQNSFSKVQEKVHSVEKPYKCEDCGKGYN
sp|Q9UK12-2|ZN222_HUMAN      ------------------------------------------------------CGKRYK
sp|Q12901|ZN155_HUMAN        ------------------------------------------------------CGRRYK
sp|Q14590|ZN235_HUMAN        KEFSWSAGLSAHQRVHTGEKPYTCQQCGKGFSQASHFHTHQRVHTGERPYICDVCCKGFS
sp|Q02386|ZNF45_HUMAN        KVFSWSSYLQAHQRVHTGEKPYKCEECGKGFSWSSSLIIHQRVHADDE------GDKDFP
                                                                                     .   

sp|Q14588|ZN234_HUMAN        WRSNLVSHHKIHAAGTFYENDENSKNIRELSEGGSSTR-------
sp|Q9NYT6|ZN226_HUMAN        WRSNLTVHHRIHVGDKSYKSNRGGKNIRESTQEKKSIK-------
sp|Q9UK10|ZN225_HUMAN        RRLNLDTLLSLFLNDT-----------------------------
sp|Q9UK13|ZN221_HUMAN        ---------------------------------------------
sp|Q9NZL3|ZN224_HUMAN        RRLNLDMHQRVHMGEKTWKCRECDMCFSQASSLRLHQNVHVGEKP
sp|Q9UK12-2|ZN222_HUMAN      RRLNLDIILSLFLNDI-----------------------------
sp|Q12901|ZN155_HUMAN        RRLNLDILLSLFLNDT-----------------------------
sp|Q14590|ZN235_HUMAN        QRSHLIYHQRVHTGGNL----------------------------
sp|Q02386|ZNF45_HUMAN        --SSEDSHRKTR---------------------------------
                                                                          
