CLUSTAL X (1.81) multiple sequence alignment


sp|Q14588|ZN234_HUMAN               GHHPFKHDVF-LLEKEKKLDIMKTATQRKGKSA
sp|Q9NYT6|ZN226_HUMAN               GHPPFKQDVS-PIERNEQLWIMTTATRRQGNLG
sp|Q9UK10|ZN225_HUMAN               GHQSLHRDTF-HFLKEEKFWMMETATQREGNLG
sp|Q9UK13|ZN221_HUMAN               GNQPFHQDTF-HFLGKEKFWKMKTTSQREGNSG
sp|Q9NZL3|ZN224_HUMAN               GHQAFHRDTF-HFLREEKIWMMKTAIQREGNSG
sp|Q9UK12-2|ZN222_HUMAN             GHQPFHGDTF-HFLREEKFWVMGTTSQREGNLG
sp|Q12901|ZN155_HUMAN               GHQPFHQDTC-HFLREEKFWMMGTATQREGNSG
sp|Q14590|ZN235_HUMAN               GHQSFKPDMISQLEREEKLWMKELQTQRGKHSG
sp|Q02386|ZNF45_HUMAN               GHQS-TPDGLPQLEREEKLWMMKMATQRDNSSG


